project:
  type: website
  output-dir: _site
  title: Showcase Curriculum for Research Software Engineering
  render:
    - "*.qmd"


website:
  title: "RSE Curriculum"
  description: ""
  navbar:
    right:
      - text: "Curriculum"
        href: generation/generated/curriculum.qmd
      - text: "ideas"
        href: general/ideas.qmd
      - text: "Job Roles"
        href: general/job_roles.qmd
      - text: "PDF-Version"
        href: _doc/RSE-Curriculum.pdf
      - text: "Glossary"
        href: general/glossary.qmd


format:
  html:
    theme: lux
    bibliography:
      - references.bib
      - external/bibliography/bibliography.bib

