sources:
  courses:
    - name: Statistical Data Analysis
      link: "https://puls.uni-potsdam.de/qisserver/pages/cs/sys/portal/hisinoneIframePage.faces?id=qis_MKSuchen_0&navigationPosition=up_modulbeschreibung%2Cqis_MKSuchen&recordRequest=true"
    - name: Mathematical Foundations of Data Science
      link: "https://puls.uni-potsdam.de/qisserver/pages/cs/sys/portal/hisinoneIframePage.faces?id=qis_MKSuchen_0&navigationPosition=up_modulbeschreibung%2Cqis_MKSuchen&recordRequest=true"
    - name: Programmieren für Data Scientists Python
      link: "https://studip.uni-goettingen.de/dispatch.php/course/details/index/d5e09a9298492991a57d59c7b2f09f98"
  programs:
    - name: UP Data Science
      link: "https://www.uni-potsdam.de/de/studium/studienangebot/master/data-science"
  curricula:
    - name: Emppfehlungen Masterstudiengänge Data Science
      link: "https://gi.de/fileadmin/GI/Hauptseite/Service/Publikationen/Empfehlungen/Empfehlungen_Masterstdiengaenge_DataScience_2021.pdf"